version: '3.4'

services:
  ducttape:
    image: ducttape
    build:
      context: .
      dockerfile: ./Dockerfile
    version: '3.1'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 3pona30
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

      